### ISSUE TITLE
Use ISO 8601 format for datetimes in JSON file

### ISSUE THREAD

**Issue by fhurta** [obbimi/Squore#17]
In [Technical](http://squore.double-yellow.be/#Technical) section you describe  format of JSON file.  There is `when` field which uses separated `date` and `time` fileds, in `timing` array there are fields `start`, `end` that concatenates date and time part using dash. 
As JSON is JavaScript Object Notation, it would be more natural to use standard datetime format which is ISO 8601:
  - it is standard so it makes integration using other languages easier
  - it contains time zone so it allows for precise time specification even if the club's web server runs in different time zone than the venue for the squash match.

**Comment by obbimi** [comment]
https://www.w3.org/TR/NOTE-datetime
