### ISSUE TITLE
Standalone APK

### ISSUE THREAD

**Issue by kekkoudesu** [obbimi/Squore#27]
Love the app (especially the name)! It's easily the best Squash scoring app around. I'd love to be able to install the app without needing to install the Google Play store.

Squore could support that by using Github Releases to distribute the standalone APK users can install without Google Play or Google Play Services.

I use [Obtainium](https://github.com/ImranR98/Obtainium) to automate updates to Android apps which supports Github Releases as a source. Most of my apps are installed this way.

Thanks!

**Comment by obbimi** [comment]
Thanks for the suggestion. I will have a look at this. Is it also possible to install an apk on wearOs in this way? Google is rejecting all my wearOS updates for the moment due to more strict (in my opinion to strict) guidelines/rules. 
Good to hear you appreciate the app!!

**Comment by kekkoudesu** [comment]
According to Google's documentation it looks like wearOS does support APKs: https://developer.android.com/distribute/best-practices/launch/distribute-wear#package-your-app

**Comment by obbimi** [comment]
Thanks for coming back. I know wearOS does support APKs. My question is more: can you install an apk on wearOS using Obtainium.

**Comment by kekkoudesu** [comment]
Ah, sorry, I'm not really familiar since I don't own a smartwatch.

I did a bit more searching and found this discussion thread: https://github.com/ImranR98/Obtainium/discussions/1470

Some of it goes over my head, but this seems to be the upshot:

> Wear Installer 2 will get you Obtainium. If you root your watch or use Shizuku, haven't tested yet, then you should be able to install stuff.

> > Why can I install stuff through Obtainium on my Samsung 21 without root, but when it comes to a Smart Watch it (root/Shizuku) is required? Grateful for any clarification (I am farily new to the Android ecosystem).

> **The ability to sidelpad an apk onto Android which has a permission for an app to do it has been removed from WearOS (WearOS is Android but with things changed, including some permissions and functions entirely removed.)**

So it seems the answer is no, at least without breaking wearOS' security by rooting the device.

That's a shame, really...

**Comment by obbimi** [comment]
I implemented a github workflow that creates a release for all the 'flavours' of my app.
https://github.com/obbimi/Squore/releases
Can you give it a try with Obtainium?
You probably need to use apk: [Squore.524-phoneTabletPost23-release-signed.apk](https://github.com/obbimi/Squore/releases/download/Release.524/Squore.524-phoneTabletPost23-release-signed.apk)

**Comment by kekkoudesu** [comment]
Wow, that was quick! Thanks so much!

I searched for "Squore" in Obtainium, found your Github repository as the first result, added it, and installed the APK you recommended. The app continues to work great.

**Comment by obbimi** [comment]
Implemented
