### ISSUE TITLE
How to get score sheet back?

### ISSUE THREAD

**Issue by kekkoudesu** [obbimi/Squore#28]
I checked the [docs](https://squore.double-yellow.be/#Scoring):

I want it to look like this when I'm sqoring:

![image](https://github.com/user-attachments/assets/8b0681ff-64ac-471b-a1d2-a8fcb6b5d77b)

> Note that in the middle of the score board a more or less 'old fashioned' score sheet is also maintained. If you do now find this useful, you can turn it off in the settings screen.

It looks like a recent update turned this off by default. I went through all the settings, but I couldn't find a way to turn the score sheet back on.

Am I missing something?

**Comment by obbimi** [comment]
By default it is still showing for me...
If it is not showing check out the option > Settings > Appearance > Layout > Show scoring history on. 
There it should present two 'checkable' options: On Device, On Chromecast. Check the first if it is not.

**Comment by kekkoudesu** [comment]
Hey, thanks for the response. Looks like it came back in the intervening period. Not sure what that was about.
