### ISSUE TITLE
Per-match PAR/best-of settings

### ISSUE THREAD

**Issue by madduck** [obbimi/Squore#33]
We just ran a Christmas tournament in which only the last games were best-of-5, while the other games were best-of-3. In addition, we chose to make it PAR15 for the lower grades, and PAR11 by default.

With the JSON feed, `numberOfPointsToWinGame` and `numberOfGamesToWinMatch` are global config settings. As are `useHandInHandOutScoring` and `tiebreakFormat`.

Would it be possible to allow each of these to be overridden for individual matches?

**Comment by obbimi** [comment]
`numberOfPointsToWinGame` and `numberOfGamesToWinMatch` can already be specified at match level. Will add other options as well.
