### ISSUE TITLE
Court names being lower-cased

### ISSUE THREAD

**Issue by madduck** [obbimi/Squore#34]
![image](https://github.com/user-attachments/assets/78f45441-2e26-408c-9ccd-10038f864092)

The feed provides these courts as "Court 1", but the UI renders these with lower case. This isn't an issue in this case, but I have definitely played tournaments where the courts were named after players, and I don't think you want a "susan devoy" court all lower-case.

**Comment by madduck** [comment]
Note that only the first letter is downcased. So the court would be called "susan Devoy", which is even worse.

**Comment by obbimi** [comment]
In fact there was some code that simply downcased every occurence of 'Court' in incoming json. This was to ensure backwards compatibility with feeds the specified "Court" in stead of "court" in their json feeds. That has been improved now to only downcase some key words provided they occur between quotes.
