### ISSUE TITLE
`config.Format` has no effect

### ISSUE THREAD

**Issue by madduck** [obbimi/Squore#39]
The [demo.matches.json] file lists `config.Format`. I provided that with my JSON, and changed it to remove the countries:

![image](https://github.com/user-attachments/assets/9c42d6e9-8506-45b6-9d75-dbae75d1491a)

But when I refresh Squore, the template seems not to apply:

![image](https://github.com/user-attachments/assets/a69393b2-ebeb-4f41-b6cd-ac2f91af0c83)

Note also how there is no ID up front (as specified in the demo, which I assume has the defaults) and the "result" at the end is actually the ID.

**Comment by madduck** [comment]
I also tried lowercase, i.e. `config.format`, but to no avail.

**Comment by obbimi** [comment]
Sorry, the example still contained the old 'Format' key. Please use 'Placeholder_Match' in stead.
This has now been corrected.
More details in <https://squore.double-yellow.be/feed/2023-11-10.Integrate-Squore-with-your-website.odt>

**Comment by madduck** [comment]
Can confirm it works with `Placeholder_Match`. Thanks.
