### ISSUE TITLE
Non-localizable texts in preferences

### ISSUE THREAD

**Issue by fhurta** [obbimi/Squore#6]
There are texts that are not localizble, in `res/xml/preferences.xml`.
In the file, search for (RegExp): `android:title="[^@].*`

**Comment by hoeveid** [comment]
In the 'next' branch resource strings have been introduced. Please take lines 4-27 of res/values/settings.xml and translate the values into Czech.

**Comment by fhurta** [comment]
I have the translations ready (it based on version of `res/values/settings.xml` from 2018-04-30). Which branch should I create the PR into (`master` or `next`)?

**Comment by obbimi** [comment]
You may use 'next' Thx
